// 1. Create a Map Variable
var mymap = L.map('map', {
    center: [0.03, 38.0],
    zoom: 8,
    maxZoom: 14,
    minZoom: 5,
    detectRetina: true // detect whether the sceen is high resolution or not.
});

// 2. Add a base map.
L.control.layers({'Basemap':baselayer},{'Mapnik':mytile}).addTo(map);

var mytile =L.control.layers('assets/tiles/{z}/{x}/{y}.png', {
    maxZoom: 9,
    tms: false,
    attribution: 'Generated by QTiles'
}).addTo(mymap);
