// 1. Create a Map Variable
var mymap = L.map('map', {
    center: [45.563613, -117.208371],
    zoom: 8,
    maxZoom: 14,
    minZoom: 5,
    detectRetina: true // detect whether the sceen is high resolution or not.
});

// 2. Add a base map.
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(mymap);

// 3. Add tile layers over base map.
L.tileLayer('wallowa/{z}/{x}/{y}.png', {
    maxZoom: 9,
    tms: false,
    attribution: 'Generated by QTiles'
}).addTo(mymap);
